### ISSUE TITLE
Move off of "one-file per table" towards "one-file per chunk"

### ISSUE THREAD

**Issue by lino-levan** [cookiedb/CookieDB#10]
We already store an index of all keys, we should ideally be using this to allow us to chunk data to minimize amount of data loaded into memory on queries.

**Comment by lino-levan** [comment]
Ref: #15

**Comment by mattfbacon** [comment]
4kb per row tsk tsk

**Comment by lino-levan** [comment]
@mattfbacon per pow?

**Comment by lino-levan** [comment]
Closed by #24
