### ISSUE TITLE
Sanitize user input

### ISSUE THREAD

**Issue by lino-levan** [cookiedb/CookieDB#9]
Some feedback from @mattfbacon on discord
> me on my way to create a table called ../../../../../etc/passwd

**Comment by lino-levan** [comment]
I'm trying to think about how to solve this. We could limit the table names to only be alphanumeric + a few extra symbols (`_`, `-`, etc)?

**Comment by mattfbacon** [comment]
Encode the table names in base64 or similar when placing them in filenames

**Comment by lino-levan** [comment]
base64 isn't url safe so I'd be a little careful about doing something on that front. Additionally, while performance is obviously not the central factor of CookieDB, encoding base64 for each request would add some blatantly unnecessary overhead.

Also, I think this issue becomes mostly irrelevant when #10 gets closed anyways so ¯\\\_(ツ)\_/¯.

**Comment by lino-levan** [comment]
Because of #24 being merged, there is no longer a security issue here. After some further thinking, I see no reason to arbitrarily prevent users from naming tables whatever they want. If a reason comes up, I may reopen but I'll close this for now.

**Comment by lino-levan** [comment]
I change my mind, we should be sanitizing user input. We should be looking at every API endpoint and making sure nothing weird happens when users try doing funky things. I realize now that there is a potential attack to make a broken document on a DB with a schema by having a property have a comma in it. I have not tested it, but this should be on our radar.

Schema:
```json
{
    "key,weird": "string"
}
```

"""Valid""" document (doesn't throw a key error):
```json
{
     "weird": "hi",
     "key": "hacked"
}
```

**Comment by lino-levan** [comment]
We should be checking for "." in key names. That would be invalid.

Edit: also in table names

also documents + schemas can't have "key" as a key
